### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by intenzemotion** [ChristopherKlay/StarRailTracker#2]
Hi. There are three corrections need to be made:
- Trial of Thirteen renamed to The Thirteen Labors.
- Draconic Opulence moved to The Memories We Share category.
- You can only get either Wordsmith or Literary Novice, never both.

**Comment by ChristopherKlay** [comment]
[Fixed](https://github.com/ChristopherKlay/StarRailTracker/blob/main/changelog.md#29072023).

Thanks for reporting these issues!
